# https://oknozor.github.io/toml-bombadil/docs/getting-started/quick-start/

# Path to your dotfiles relative to your $HOME directory
dotfiles_dir = "Dotfiles"

[settings]
# An array of toml files paths containing the variables to inject in your templatized dotfiles
# You can have multiple var files as long as variable names does not colide.
# vars = [ "vars.toml" ]

# An array of post install shell commands
# posthooks = [ "sway reload" ]

[settings.dots]

# A dot entry representing a symlink, `source` is relative to `dotfiles_dir`
# and `target` shall be relative to $HOME directory or absolute.
# sway = { source = "sway", target = ".config/sway" }

# You can have as many dot entry as you want, linking files or directories
alacritty = { source = "config/alacritty", target = ".config/alacritty" }
environment = { source = "config/environment.d", target = ".config/environment.d"}
fonts = { source = "config/fontconfig", target = ".config/fontconfig" }
editorconfig = { source = "editorconfig", target = ".editorconfig" }
gitconfig = { source = "gitconfig", target = ".gitconfig" }
irbrc = { source = "irbrc", target = ".irbrc" }
mangohud = { source = "config/MangoHud", target = ".config/MangoHud" }
pipewire = { source = "config/pipewire", target = ".config/pipewire"}
pryrc = { source = "pryrc", target = ".pryrc" }
starship = { source = "config/starship.toml", target = ".config/starship.toml" }
vimrc = { source = "vimrc", target = ".vimrc" }
zlogin = { source = "zlogin", target = ".zlogin" }
zshenv = { source = "zshenv", target = ".zshenv" }
zshrc = { source = "zshrc", target = ".zshrc" }
